version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  bandit:
    enabled: true
  pep8:
    enabled: true
    max-line-length: 180
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      minimum_severity: major
      tests_patterns:
        - pythresh/test/**
exclude_patterns:
  - "examples/"
  - "**/test/"
