repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: name-tests-test
        always_run: true
        args: [--pytest-test-first]
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --fix, --line-length=180]
        exclude: "\\.ipynb$"
        name: Lint code
